# ==========================================
# SECTOR MAP EMITEN BEI (IDX-IC) - BAGIAN 1
# ==========================================

SECTOR_MAP = {
    # --- ABJAD A ---
    "AADI.JK": "Energi",
    "AALI.JK": "Barang Konsumen Primer",
    "ABBA.JK": "Barang Konsumen Non-Primer",
    "ABDA.JK": "Keuangan",
    "ABMM.JK": "Energi",
    "ACES.JK": "Barang Konsumen Non-Primer",
    "ACRO.JK": "Perindustrian",
    "ACST.JK": "Infrastruktur",
    "ADES.JK": "Barang Konsumen Primer",
    "ADHI.JK": "Infrastruktur",
    "ADMF.JK": "Keuangan",
    "ADMG.JK": "Barang Baku",
    "ADMR.JK": "Energi",
    "ADRO.JK": "Energi",
    "AEGS.JK": "Perindustrian",
    "AGAR.JK": "Barang Konsumen Primer",
    "AGII.JK": "Barang Baku",
    "AGRO.JK": "Keuangan",
    "AGRS.JK": "Keuangan",
    "AHAP.JK": "Keuangan",
    "AIMS.JK": "Barang Konsumen Non-Primer",
    "AISA.JK": "Barang Konsumen Primer",
    "AKKU.JK": "Barang Konsumen Non-Primer",
    "AKPI.JK": "Barang Baku",
    "AKRA.JK": "Energi",
    "AKSI.JK": "Transportasi & Logistik",
    "ALDO.JK": "Barang Baku",
    "ALII.JK": "Barang Konsumen Primer",
    "ALKA.JK": "Barang Baku",
    "ALMI.JK": "Barang Baku",
    "ALTO.JK": "Barang Konsumen Primer",
    "AMAG.JK": "Keuangan",
    "AMAN.JK": "Properti & Real Estat",
    "AMAR.JK": "Keuangan",
    "AMFG.JK": "Barang Baku",
    "AMIN.JK": "Perindustrian",
    "AMMM.JK": "Energi",
    "AMMS.JK": "Transportasi & Logistik",
    "AMMN.JK": "Barang Baku",
    "AMOR.JK": "Barang Konsumen Non-Primer",
    "AMRT.JK": "Barang Konsumen Primer",
    "ANDI.JK": "Properti & Real Estat",
    "ANJT.JK": "Barang Konsumen Primer",
    "ANTM.JK": "Barang Baku",
    "APEX.JK": "Energi",
    "APIC.JK": "Keuangan",
    "APII.JK": "Barang Konsumen Non-Primer",
    "APLI.JK": "Barang Baku",
    "APLN.JK": "Properti & Real Estat",
    "ARCI.JK": "Barang Baku",
    "ARGO.JK": "Barang Konsumen Non-Primer",
    "AREA.JK": "Teknologi",
    "ARII.JK": "Barang Konsumen Primer",
    "ARKA.JK": "Perindustrian",
    "ARKO.JK": "Infrastruktur",
    "ARMY.JK": "Properti & Real Estat",
    "ARNA.JK": "Barang Baku",
    "ARTA.JK": "Keuangan",
    "ARTI.JK": "Energi",
    "ARTO.JK": "Keuangan",
    "ASAS.JK": "Barang Konsumen Non-Primer",
    "ASBI.JK": "Keuangan",
    "ASDM.JK": "Kesehatan",
    "ASGR.JK": "Teknologi",
    "ASHA.JK": "Barang Konsumen Primer",
    "ASII.JK": "Barang Konsumen Non-Primer",
    "ASJT.JK": "Keuangan",
    "ASLI.JK": "Perindustrian",
    "ASLC.JK": "Barang Konsumen Non-Primer",
    "ASMI.JK": "Keuangan",
    "ASPI.JK": "Perindustrian",
    "ASPR.JK": "Properti & Real Estat",
    "ASRI.JK": "Properti & Real Estat",
    "ASRM.JK": "Keuangan",
    "ASSA.JK": "Transportasi & Logistik",
    "ATAP.JK": "Barang Baku",
    "ATIC.JK": "Teknologi",
    "ATLA.JK": "Energi",
    "AUTO.JK": "Barang Konsumen Non-Primer",
    "AVIA.JK": "Barang Baku",
    "AWAN.JK": "Teknologi",
    "AXIO.JK": "Teknologi",
    "AYAM.JK": "Barang Konsumen Primer",
    "AYLS.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD B ---
    "BABP.JK": "Keuangan",
    "BABY.JK": "Barang Konsumen Non-Primer",
    "BACA.JK": "Keuangan",
    "BAIK.JK": "Barang Konsumen Non-Primer",
    "BAJA.JK": "Barang Baku",
    "BALI.JK": "Infrastruktur",
    "BANK.JK": "Keuangan",
    "BAPA.JK": "Properti & Real Estat",
    "BAPI.JK": "Properti & Real Estat",
    "BATA.JK": "Barang Konsumen Non-Primer",
    "BATR.JK": "Perindustrian",
    "BAUT.JK": "Barang Baku",
    "BAYU.JK": "Transportasi & Logistik",
    "BBCA.JK": "Keuangan",
    "BBHI.JK": "Keuangan",
    "BBKP.JK": "Keuangan",
    "BBLD.JK": "Keuangan",
    "BBMD.JK": "Keuangan",
    "BBNI.JK": "Keuangan",
    "BBRI.JK": "Keuangan",
    "BBRM.JK": "Transportasi & Logistik",
    "BBSI.JK": "Keuangan",
    "BBSS.JK": "Infrastruktur",
    "BBTN.JK": "Keuangan",
    "BBYB.JK": "Keuangan",
    "BCAP.JK": "Keuangan",
    "BCIC.JK": "Keuangan",
    "BCIP.JK": "Properti & Real Estat",
    "BDKR.JK": "Infrastruktur",
    "BDMN.JK": "Keuangan",
    "BEBS.JK": "Infrastruktur",
    "BEEF.JK": "Barang Konsumen Primer",
    "BEER.JK": "Barang Konsumen Primer",
    "BEKS.JK": "Keuangan",
    "BELI.JK": "Barang Konsumen Non-Primer",
    "BELL.JK": "Barang Konsumen Non-Primer",
    "BEST.JK": "Properti & Real Estat",
    "BESS.JK": "Keuangan",
    "BFIN.JK": "Keuangan",
    "BGTG.JK": "Keuangan",
    "BHAT.JK": "Infrastruktur",
    "BHIT.JK": "Keuangan",
    "BIKA.JK": "Properti & Real Estat",
    "BIKE.JK": "Barang Konsumen Non-Primer",
    "BIMA.JK": "Kesehatan",
    "BINA.JK": "Keuangan",
    "BINO.JK": "Barang Konsumen Non-Primer",
    "BIPI.JK": "Energi",
    "BIPP.JK": "Properti & Real Estat",
    "BIRD.JK": "Transportasi & Logistik",
    "BISI.JK": "Barang Konsumen Primer",
    "BJBR.JK": "Keuangan",
    "BJTM.JK": "Keuangan",
    "BKDP.JK": "Properti & Real Estat",
    "BKSL.JK": "Properti & Real Estat",
    "BKSW.JK": "Properti & Real Estat",
    "BLES.JK": "Barang Baku",
    "BLOG.JK": "Teknologi",
    "BLTA.JK": "Transportasi & Logistik",
    "BLTZ.JK": "Barang Konsumen Non-Primer",
    "BLUE.JK": "Barang Konsumen Non-Primer",
    "BMAS.JK": "Keuangan",
    "BMBL.JK": "Barang Konsumen Non-Primer",
    "BMHS.JK": "Kesehatan",
    "BMRI.JK": "Keuangan",
    "BMSR.JK": "Barang Baku",
    "BMTR.JK": "Barang Konsumen Non-Primer",
    "BNBA.JK": "Keuangan",
    "BNBR.JK": "Perindustrian",
    "BNGA.JK": "Keuangan",
    "BNII.JK": "Keuangan",
    "BNLI.JK": "Keuangan",
    "BOAT.JK": "Transportasi & Logistik",
    "BOBA.JK": "Barang Konsumen Primer",
    "BOGA.JK": "Barang Konsumen Non-Primer",
    "BOLA.JK": "Barang Konsumen Non-Primer",
    "BOLT.JK": "Barang Baku",
    "BOSS.JK": "Energi",
    "BPFI.JK": "Keuangan",
    "BPII.JK": "Keuangan",
    "BPTR.JK": "Transportasi & Logistik",
    "BRAM.JK": "Barang Konsumen Non-Primer",
    "BREN.JK": "Infrastruktur",
    "BRIS.JK": "Keuangan",
    "BRMS.JK": "Barang Baku",
    "BRNA.JK": "Barang Konsumen Non-Primer",
    "BRPT.JK": "Barang Baku",
    "BRRC.JK": "Properti & Real Estat",
    "BSBK.JK": "Properti & Real Estat",
    "BSDE.JK": "Properti & Real Estat",
    "BSIM.JK": "Keuangan",
    "BSML.JK": "Transportasi & Logistik",
    "BSSR.JK": "Energi",
    "BSWD.JK": "Keuangan",
    "BTEK.JK": "Barang Konsumen Primer",
    "BTEL.JK": "Infrastruktur",
    "BTON.JK": "Barang Baku",
    "BTPN.JK": "Keuangan",
    "BTPS.JK": "Keuangan",
    "BUAH.JK": "Barang Konsumen Primer",
    "BUDI.JK": "Barang Baku",
    "BUKA.JK": "Teknologi",
    "BUKK.JK": "Infrastruktur",
    "BULL.JK": "Transportasi & Logistik",
    "BUMI.JK": "Energi",
    "BUVA.JK": "Barang Konsumen Non-Primer",
    "BVIC.JK": "Keuangan",
    "BWPT.JK": "Barang Konsumen Primer",
    "BYAN.JK": "Energi",
    # --- ABJAD C ---
    "CAKK.JK": "Barang Baku",
    "CAMP.JK": "Barang Konsumen Primer",
    "CANI.JK": "Transportasi & Logistik",
    "CARE.JK": "Kesehatan",
    "CARS.JK": "Barang Konsumen Non-Primer",
    "CASA.JK": "Keuangan",
    "CASH.JK": "Teknologi",
    "CASS.JK": "Transportasi & Logistik",
    "CBDK.JK": "Kesehatan",
    "CBPE.JK": "Infrastruktur",
    "CBRE.JK": "Transportasi & Logistik",
    "CBUT.JK": "Barang Konsumen Primer",
    "CCSI.JK": "Barang Baku",
    "CDIA.JK": "Kesehatan",
    "CEKA.JK": "Barang Konsumen Primer",
    "CENT.JK": "Infrastruktur",
    "CFIN.JK": "Keuangan",
    "CGAS.JK": "Infrastruktur",
    "CHEK.JK": "Barang Konsumen Non-Primer",
    "CHEM.JK": "Barang Baku",
    "CHIP.JK": "Teknologi",
    "CINT.JK": "Barang Konsumen Non-Primer",
    "CITA.JK": "Barang Baku",
    "CITY.JK": "Properti & Real Estat",
    "CLAY.JK": "Barang Konsumen Non-Primer",
    "CLEO.JK": "Barang Konsumen Primer",
    "CLPI.JK": "Barang Baku",
    "CMNP.JK": "Infrastruktur",
    "CMNT.JK": "Barang Baku",
    "CMPP.JK": "Transportasi & Logistik",
    "CMRY.JK": "Barang Konsumen Primer",
    "CNKO.JK": "Energi",
    "CNMA.JK": "Barang Konsumen Non-Primer",
    "CNTX.JK": "Barang Konsumen Non-Primer",
    "COAL.JK": "Energi",
    "COCO.JK": "Barang Konsumen Primer",
    "COIN.JK": "Perindustrian",
    "COWL.JK": "Properti & Real Estat",
    "CPIN.JK": "Barang Konsumen Primer",
    "CPRI.JK": "Barang Konsumen Non-Primer",
    "CPRO.JK": "Barang Konsumen Primer",
    "CRAB.JK": "Barang Konsumen Primer",
    "CRSN.JK": "Barang Baku",
    "CSAN.JK": "Barang Baku",
    "CSAP.JK": "Perindustrian",
    "CSIS.JK": "Transportasi & Logistik",
    "CSMI.JK": "Barang Baku",
    "CSRA.JK": "Barang Konsumen Primer",
    "CTBN.JK": "Perindustrian",
    "CTRA.JK": "Properti & Real Estat",
    "CTTH.JK": "Barang Konsumen Non-Primer",
    "CUAN.JK": "Energi",
    "CYBR.JK": "Teknologi",
    # --- ABJAD D ---
    "DAAZ.JK": "Perindustrian",
    "DADA.JK": "Properti & Real Estat",
    "DART.JK": "Properti & Real Estat",
    "DATA.JK": "Teknologi",
    "DAYA.JK": "Barang Konsumen Non-Primer",
    "DCII.JK": "Teknologi",
    "DEAL.JK": "Perindustrian",
    "DEFI.JK": "Keuangan",
    "DEPO.JK": "Barang Konsumen Non-Primer",
    "DEWA.JK": "Infrastruktur",
    "DEWI.JK": "Barang Konsumen Primer",
    "DFAM.JK": "Barang Konsumen Non-Primer",
    "DGIK.JK": "Infrastruktur",
    "DGNS.JK": "Kesehatan",
    "DGWG.JK": "Barang Konsumen Non-Primer",
    "DIGI.JK": "Teknologi",
    "DILD.JK": "Properti & Real Estat",
    "DIVA.JK": "Teknologi",
    "DKFT.JK": "Barang Baku",
    "DKHH.JK": "Kesehatan",
    "DLTA.JK": "Barang Konsumen Primer",
    "DMAS.JK": "Properti & Real Estat",
    "DMMX.JK": "Teknologi",
    "DMND.JK": "Barang Konsumen Primer",
    "DNAR.JK": "Keuangan",
    "DNET.JK": "Teknologi",
    "DOID.JK": "Energi",
    "DOOH.JK": "Barang Konsumen Non-Primer",
    "DOSS.JK": "Barang Konsumen Non-Primer",
    "DPNS.JK": "Barang Baku",
    "DPUM.JK": "Barang Konsumen Primer",
    "DRMA.JK": "Barang Konsumen Non-Primer",
    "DSFI.JK": "Barang Konsumen Primer",
    "DSNG.JK": "Barang Konsumen Primer",
    "DSSA.JK": "Energi",
    "DUCK.JK": "Barang Konsumen Non-Primer",
    "DUTI.JK": "Properti & Real Estat",
    "DVLA.JK": "Kesehatan",
    "DWGL.JK": "Perindustrian",
    "DYAN.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD E ---
    "EAST.JK": "Barang Konsumen Non-Primer",
    "ECII.JK": "Barang Konsumen Non-Primer",
    "EDGE.JK": "Teknologi",
    "EKAD.JK": "Barang Baku",
    "ELIT.JK": "Teknologi",
    "ELPI.JK": "Transportasi & Logistik",
    "ELSA.JK": "Energi",
    "ELTY.JK": "Properti & Real Estat",
    "EMAS.JK": "Barang Konsumen Non-Primer",
    "EMDE.JK": "Properti & Real Estat",
    "EMTK.JK": "Teknologi",
    "ENAK.JK": "Barang Konsumen Non-Primer",
    "ENRG.JK": "Energi",
    "ENZO.JK": "Barang Konsumen Non-Primer",
    "EPAC.JK": "Perindustrian",
    "EPMT.JK": "Kesehatan",
    "ERAA.JK": "Barang Konsumen Non-Primer",
    "ERAL.JK": "Barang Konsumen Non-Primer",
    "ERTX.JK": "Barang Konsumen Non-Primer",
    "ESIP.JK": "Barang Baku",
    "ESSA.JK": "Energi",
    "ESTA.JK": "Keuangan",
    "ESTI.JK": "Barang Konsumen Non-Primer",
    "ETWA.JK": "Barang Konsumen Primer",
    "EURO.JK": "Barang Konsumen Non-Primer",
    "EXCL.JK": "Infrastruktur",
    # --- ABJAD F ---
    "FAPA.JK": "Barang Konsumen Primer",
    "FAST.JK": "Barang Konsumen Non-Primer",
    "FASW.JK": "Barang Baku",
    "FILM.JK": "Barang Konsumen Non-Primer",
    "FIMP.JK": "Barang Konsumen Non-Primer",
    "FIRE.JK": "Energi",
    "FISH.JK": "Barang Konsumen Primer",
    "FITT.JK": "Barang Konsumen Non-Primer",
    "FLMC.JK": "Barang Konsumen Non-Primer",
    "FMII.JK": "Properti & Real Estat",
    "FOLK.JK": "Barang Konsumen Non-Primer",
    "FOOD.JK": "Barang Konsumen Primer",
    "FORE.JK": "Barang Konsumen Non-Primer",
    "FORU.JK": "Barang Konsumen Non-Primer",
    "FPNI.JK": "Barang Baku",
    "FUJI.JK": "Keuangan",
    "FUTR.JK": "Teknologi",
    "FWCT.JK": "Barang Baku",
    # --- ABJAD G ---
    "GAMA.JK": "Properti & Real Estat",
    "GDST.JK": "Barang Baku",
    "GDYR.JK": "Barang Konsumen Non-Primer",
    "GEMA.JK": "Barang Konsumen Non-Primer",
    "GEMS.JK": "Energi",
    "GGRM.JK": "Barang Konsumen Primer",
    "GHON.JK": "Infrastruktur",
    "GIAA.JK": "Transportasi & Logistik",
    "GJTL.JK": "Barang Konsumen Non-Primer",
    "GLOB.JK": "Barang Konsumen Non-Primer",
    "GLVA.JK": "Teknologi",
    "GMFI.JK": "Transportasi & Logistik",
    "GMTD.JK": "Properti & Real Estat",
    "GOLD.JK": "Barang Konsumen Non-Primer",
    "GOLF.JK": "Barang Konsumen Non-Primer",
    "GOLL.JK": "Barang Konsumen Primer",
    "GOOD.JK": "Barang Konsumen Primer",
    "GOTO.JK": "Teknologi",
    "GPRA.JK": "Properti & Real Estat",
    "GPSO.JK": "Perindustrian",
    "GRIA.JK": "Properti & Real Estat",
    "GRPH.JK": "Barang Konsumen Non-Primer",
    "GRPM.JK": "Barang Konsumen Primer",
    "GSMF.JK": "Keuangan",
    "GTBO.JK": "Energi",
    "GTRA.JK": "Transportasi & Logistik",
    "GTSI.JK": "Transportasi & Logistik",
    "GULA.JK": "Barang Konsumen Primer",
    "GUNA.JK": "Barang Konsumen Primer",
    "GWSA.JK": "Properti & Real Estat",
    "GZCO.JK": "Barang Konsumen Primer",
    # --- ABJAD H ---
    "HADE.JK": "Transportasi & Logistik",
    "HAIS.JK": "Transportasi & Logistik",
    "HAJJ.JK": "Barang Konsumen Non-Primer",
    "HALO.JK": "Kesehatan",
    "HATM.JK": "Transportasi & Logistik",
    "HBAT.JK": "Barang Baku",
    "HDFA.JK": "Keuangan",
    "HDIT.JK": "Teknologi",
    "HEAL.JK": "Kesehatan",
    "HELI.JK": "Transportasi & Logistik",
    "HERO.JK": "Barang Konsumen Primer",
    "HEXA.JK": "Perindustrian",
    "HGII.JK": "Keuangan",
    "HILL.JK": "Energi",
    "HITS.JK": "Transportasi & Logistik",
    "HKMU.JK": "Perindustrian",
    "HMSP.JK": "Barang Konsumen Primer",
    "HOKI.JK": "Barang Konsumen Primer",
    "HOME.JK": "Barang Konsumen Non-Primer",
    "HOMI.JK": "Properti & Real Estat",
    "HOPE.JK": "Kesehatan",
    "HOTL.JK": "Barang Konsumen Non-Primer",
    "HRME.JK": "Barang Konsumen Non-Primer",
    "HRTA.JK": "Barang Konsumen Non-Primer",
    "HRUM.JK": "Energi",
    "HUMI.JK": "Transportasi & Logistik",
    "HYGN.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD I ---
    "IATA.JK": "Energi",
    "IBFN.JK": "Keuangan",
    "IBOS.JK": "Barang Konsumen Primer",
    "IBST.JK": "Infrastruktur",
    "ICBP.JK": "Barang Konsumen Primer",
    "ICON.JK": "Barang Konsumen Non-Primer",
    "IDEA.JK": "Barang Konsumen Non-Primer",
    "IDPR.JK": "Infrastruktur",
    "IFII.JK": "Barang Baku",
    "IFSH.JK": "Energi",
    "IGAR.JK": "Barang Baku",
    "IIKP.JK": "Barang Konsumen Primer",
    "IKAI.JK": "Barang Baku",
    "IKAN.JK": "Barang Konsumen Primer",
    "IKBI.JK": "Barang Konsumen Non-Primer",
    "IKPM.JK": "Barang Baku",
    "IMAS.JK": "Barang Konsumen Non-Primer",
    "IMJS.JK": "Keuangan",
    "IMPC.JK": "Barang Baku",
    "INAF.JK": "Kesehatan",
    "INAI.JK": "Barang Baku",
    "INCF.JK": "Keuangan",
    "INCI.JK": "Barang Baku",
    "INCO.JK": "Barang Baku",
    "INDF.JK": "Barang Konsumen Primer",
    "INDO.JK": "Barang Konsumen Primer",
    "INDR.JK": "Barang Konsumen Non-Primer",
    "INDS.JK": "Barang Konsumen Non-Primer",
    "INDX.JK": "Barang Konsumen Non-Primer",
    "INDY.JK": "Energi",
    "INET.JK": "Teknologi",
    "INKP.JK": "Barang Baku",
    "INOV.JK": "Barang Konsumen Non-Primer",
    "INPC.JK": "Keuangan",
    "INPL.JK": "Properti & Real Estat",
    "INPP.JK": "Properti & Real Estat",
    "INPS.JK": "Transportasi & Logistik",
    "INRU.JK": "Barang Baku",
    "INTA.JK": "Perindustrian",
    "INTD.JK": "Barang Konsumen Non-Primer",
    "INTP.JK": "Barang Baku",
    "IOTF.JK": "Teknologi",
    "IPAC.JK": "Perindustrian",
    "IPCC.JK": "Transportasi & Logistik",
    "IPCM.JK": "Transportasi & Logistik",
    "IPOL.JK": "Barang Baku",
    "IPPE.JK": "Energi",
    "IPTV.JK": "Barang Konsumen Non-Primer",
    "IRRA.JK": "Kesehatan",
    "IRSX.JK": "Teknologi",
    "ISAP.JK": "Barang Konsumen Non-Primer",
    "ISAT.JK": "Infrastruktur",
    "ISEA.JK": "Barang Konsumen Primer",
    "ISSP.JK": "Barang Baku",
    "ITIC.JK": "Barang Konsumen Primer",
    "ITMA.JK": "Energi",
    "ITMG.JK": "Energi",
    # --- ABJAD J ---
    "JARR.JK": "Barang Konsumen Primer",
    "JAST.JK": "Infrastruktur",
    "JATI.JK": "Teknologi",
    "JAWA.JK": "Infrastruktur",
    "JAYA.JK": "Infrastruktur",
    "JECC.JK": "Barang Baku",
    "JGLE.JK": "Barang Konsumen Non-Primer",
    "JIHD.JK": "Properti & Real Estat",
    "JKON.JK": "Infrastruktur",
    "JMAS.JK": "Keuangan",
    "JPFA.JK": "Barang Konsumen Primer",
    "JRPT.JK": "Properti & Real Estat",
    "JSMR.JK": "Infrastruktur",
    "JSPT.JK": "Properti & Real Estat",
    "JSKY.JK": "Perindustrian",
    "JTPE.JK": "Perindustrian",
    # --- ABJAD K ---
    "KAEF.JK": "Kesehatan",
    "KAQI.JK": "Perindustrian",
    "KARW.JK": "Transportasi & Logistik",
    "KAYU.JK": "Barang Baku",
    "KBAG.JK": "Properti & Real Estat",
    "KBLI.JK": "Barang Baku",
    "KBLM.JK": "Barang Baku",
    "KBLV.JK": "Barang Konsumen Non-Primer",
    "KBRI.JK": "Perindustrian",
    "KDSI.JK": "Barang Baku",
    "KDTN.JK": "Barang Konsumen Non-Primer",
    "KEEN.JK": "Infrastruktur",
    "KEJU.JK": "Barang Konsumen Primer",
    "KETR.JK": "Infrastruktur",
    "KIAS.JK": "Barang Baku",
    "KICI.JK": "Barang Konsumen Non-Primer",
    "KIJA.JK": "Properti & Real Estat",
    "KING.JK": "Perindustrian",
    "KINO.JK": "Barang Konsumen Primer",
    "KIOS.JK": "Teknologi",
    "KJEN.JK": "Barang Konsumen Non-Primer",
    "KKES.JK": "Kesehatan",
    "KKGI.JK": "Energi",
    "KLAS.JK": "Barang Baku",
    "KLBF.JK": "Kesehatan",
    "KLIN.JK": "Perindustrian",
    "KMDS.JK": "Barang Konsumen Primer",
    "KMTR.JK": "Perindustrian",
    "KOBI.JK": "Barang Konsumen Non-Primer",
    "KOBX.JK": "Perindustrian",
    "KOCI.JK": "Properti & Real Estat",
    "KOIN.JK": "Barang Baku",
    "KOKA.JK": "Infrastruktur",
    "KONI.JK": "Barang Konsumen Non-Primer",
    "KOPI.JK": "Barang Konsumen Primer",
    "KOTA.JK": "Properti & Real Estat",
    "KPIG.JK": "Properti & Real Estat",
    "KRAS.JK": "Barang Baku",
    "KREN.JK": "Keuangan",
    "KRYA.JK": "Infrastruktur",
    "KSIX.JK": "Barang Konsumen Non-Primer",
    "KUAS.JK": "Infrastruktur",
    # --- ABJAD L ---
    "LABA.JK": "Teknologi",
    "LABS.JK": "Kesehatan",
    "LAJU.JK": "Transportasi & Logistik",
    "LAND.JK": "Properti & Real Estat",
    "LAPD.JK": "Barang Baku",
    "LCGP.JK": "Barang Konsumen Non-Primer",
    "LCKM.JK": "Perindustrian",
    "LEAD.JK": "Transportasi & Logistik",
    "LFLO.JK": "Barang Konsumen Non-Primer",
    "LIFE.JK": "Keuangan",
    "LINK.JK": "Infrastruktur",
    "LION.JK": "Barang Baku",
    "LIVE.JK": "Barang Konsumen Non-Primer",
    "LMAX.JK": "Keuangan",
    "LMAS.JK": "Teknologi",
    "LMPI.JK": "Barang Konsumen Non-Primer",
    "LMSH.JK": "Barang Baku",
    "LOPI.JK": "Barang Konsumen Non-Primer",
    "LPCK.JK": "Properti & Real Estat",
    "LPGI.JK": "Keuangan",
    "LPIN.JK": "Keuangan",
    "LPKR.JK": "Properti & Real Estat",
    "LPLI.JK": "Barang Konsumen Non-Primer",
    "LPPF.JK": "Barang Konsumen Non-Primer",
    "LPPS.JK": "Keuangan",
    "LRNA.JK": "Transportasi & Logistik",
    "LSIP.JK": "Barang Konsumen Primer",
    "LTLS.JK": "Barang Baku",
    "LUCY.JK": "Barang Konsumen Non-Primer",
    "LUCK.JK": "Teknologi",
    # --- ABJAD M ---
    "MABA.JK": "Barang Konsumen Non-Primer",
    "MAGP.JK": "Barang Konsumen Primer",
    "MAHA.JK": "Transportasi & Logistik",
    "MAIN.JK": "Barang Konsumen Primer",
    "MANG.JK": "Barang Konsumen Non-Primer",
    "MAPB.JK": "Barang Konsumen Non-Primer",
    "MAPI.JK": "Barang Konsumen Non-Primer",
    "MAPA.JK": "Barang Konsumen Non-Primer",
    "MARI.JK": "Barang Konsumen Non-Primer",
    "MARK.JK": "Perindustrian",
    "MASB.JK": "Keuangan",
    "MAXI.JK": "Barang Konsumen Primer",
    "MAYA.JK": "Keuangan",
    "MBAP.JK": "Energi",
    "MBMA.JK": "Barang Baku",
    "MBSS.JK": "Transportasi & Logistik",
    "MBTO.JK": "Barang Konsumen Primer",
    "MCAS.JK": "Teknologi",
    "MCOL.JK": "Energi",
    "MCOR.JK": "Keuangan",
    "MDIA.JK": "Barang Konsumen Non-Primer",
    "MDKA.JK": "Barang Baku",
    "MDKI.JK": "Barang Baku",
    "MDLA.JK": "Properti & Real Estat",
    "MDLN.JK": "Properti & Real Estat",
    "MDRN.JK": "Barang Konsumen Non-Primer",
    "MEDC.JK": "Energi",
    "MEDS.JK": "Kesehatan",
    "MEGA.JK": "Keuangan",
    "MEJA.JK": "Barang Konsumen Non-Primer",
    "MENN.JK": "Transportasi & Logistik",
    "MERI.JK": "Keuangan",
    "MERK.JK": "Kesehatan",
    "META.JK": "Infrastruktur",
    "MFMI.JK": "Barang Baku",
    "MGNA.JK": "Barang Konsumen Non-Primer",
    "MGRO.JK": "Barang Konsumen Primer",
    "MHKI.JK": "Barang Baku",
    "MICE.JK": "Barang Konsumen Non-Primer",
    "MIDI.JK": "Barang Konsumen Primer",
    "MIKA.JK": "Kesehatan",
    "MINE.JK": "Energi",
    "MINA.JK": "Barang Konsumen Primer",
    "MIRA.JK": "Perindustrian",
    "MITI.JK": "Transportasi & Logistik",
    "MKAP.JK": "Barang Konsumen Primer",
    "MKPI.JK": "Properti & Real Estat",
    "MKNT.JK": "Barang Konsumen Non-Primer",
    "MKTR.JK": "Barang Konsumen Primer",
    "MLBI.JK": "Barang Konsumen Primer",
    "MLIA.JK": "Barang Baku",
    "MLPL.JK": "Teknologi",
    "MLPT.JK": "Teknologi",
    "MMIX.JK": "Barang Konsumen Non-Primer",
    "MMLP.JK": "Properti & Real Estat",
    "MNCN.JK": "Barang Konsumen Non-Primer",
    "MOLI.JK": "Barang Baku",
    "MORA.JK": "Infrastruktur",
    "MPMX.JK": "Barang Konsumen Non-Primer",
    "MPOW.JK": "Perindustrian",
    "MPPA.JK": "Barang Konsumen Primer",
    "MPXL.JK": "Transportasi & Logistik",
    "MPRO.JK": "Properti & Real Estat",
    "MRAT.JK": "Barang Konsumen Primer",
    "MREI.JK": "Keuangan",
    "MSIE.JK": "Infrastruktur",
    "MSIN.JK": "Barang Konsumen Non-Primer",
    "MSKY.JK": "Barang Konsumen Non-Primer",
    "MSJA.JK": "Barang Konsumen Primer",
    "MSTI.JK": "Teknologi",
    "MTDL.JK": "Teknologi",
    "MTEL.JK": "Infrastruktur",
    "MTFN.JK": "Keuangan",
    "MTLA.JK": "Properti & Real Estat",
    "MTMH.JK": "Kesehatan",
    "MTPS.JK": "Infrastruktur",
    "MTRA.JK": "Barang Konsumen Non-Primer",
    "MTSM.JK": "Barang Konsumen Non-Primer",
    "MTWI.JK": "Barang Konsumen Primer",
    "MUTU.JK": "Perindustrian",
    "MYOH.JK": "Kesehatan",
    "MYOR.JK": "Barang Konsumen Primer",
    "MYTX.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD N ---
    "NAIK.JK": "Transportasi & Logistik",
    "NANO.JK": "Teknologi",
    "NASA.JK": "Barang Konsumen Non-Primer",
    "NASI.JK": "Barang Konsumen Primer",
    "NATO.JK": "Barang Konsumen Non-Primer",
    "NAYZ.JK": "Barang Konsumen Primer",
    "NCKL.JK": "Barang Baku",
    "NELY.JK": "Transportasi & Logistik",
    "NEST.JK": "Barang Konsumen Primer",
    "NETV.JK": "Barang Konsumen Non-Primer",
    "NFCX.JK": "Teknologi",
    "NICE.JK": "Barang Baku",
    "NICK.JK": "Perindustrian",
    "NICL.JK": "Barang Baku",
    "NIKL.JK": "Barang Baku",
    "NINE.JK": "Barang Konsumen Primer",
    "NIRO.JK": "Properti & Real Estat",
    "NISP.JK": "Keuangan",
    "NOBU.JK": "Keuangan",
    "NPGF.JK": "Barang Konsumen Primer",
    "NRCA.JK": "Infrastruktur",
    "NSSS.JK": "Barang Konsumen Primer",
    "NTBK.JK": "Keuangan",
    "NUSA.JK": "Properti & Real Estat",
    "NZIA.JK": "Properti & Real Estat",
    # --- ABJAD O ---
    "OASA.JK": "Infrastruktur",
    "OBAT.JK": "Kesehatan",
    "OBMD.JK": "Barang Baku",
    "OCAP.JK": "Keuangan",
    "OILS.JK": "Barang Baku",
    "OKAS.JK": "Energi",
    "OLIV.JK": "Barang Konsumen Non-Primer",
    "OMED.JK": "Kesehatan",
    "OMRE.JK": "Properti & Real Estat",
    "OPMS.JK": "Perindustrian",
    # --- ABJAD P ---
    "PACK.JK": "Barang Baku",
    "PADA.JK": "Barang Konsumen Non-Primer",
    "PADI.JK": "Teknologi",
    "PALM.JK": "Barang Konsumen Primer",
    "PAMG.JK": "Keuangan",
    "PANI.JK": "Properti & Real Estat",
    "PANR.JK": "Barang Konsumen Non-Primer",
    "PANS.JK": "Keuangan",
    "PART.JK": "Perindustrian",
    "PBRX.JK": "Barang Konsumen Non-Primer",
    "PBID.JK": "Barang Baku",
    "PBSA.JK": "Perindustrian",
    "PCAR.JK": "Barang Konsumen Non-Primer",
    "PDES.JK": "Teknologi",
    "PDPP.JK": "Barang Baku",
    "PEGE.JK": "Keuangan",
    "PEHA.JK": "Kesehatan",
    "PEVE.JK": "Transportasi & Logistik",
    "PGAS.JK": "Infrastruktur",
    "PGEO.JK": "Infrastruktur",
    "PGJO.JK": "Barang Konsumen Non-Primer",
    "PGUN.JK": "Barang Konsumen Primer",
    "PGLI.JK": "Barang Konsumen Non-Primer",
    "PICO.JK": "Barang Baku",
    "PIPA.JK": "Barang Baku",
    "PJAA.JK": "Barang Konsumen Non-Primer",
    "PJHB.JK": "Infrastruktur",
    "PKPK.JK": "Infrastruktur",
    "PLAN.JK": "Barang Konsumen Primer",
    "PLAS.JK": "Barang Konsumen Non-Primer",
    "PLIN.JK": "Properti & Real Estat",
    "PMJS.JK": "Perindustrian",
    "PMMP.JK": "Barang Konsumen Primer",
    "PMUI.JK": "Perindustrian",
    "PNBN.JK": "Keuangan",
    "PNBS.JK": "Keuangan",
    "PNGO.JK": "Barang Konsumen Primer",
    "PNIN.JK": "Keuangan",
    "PNLF.JK": "Keuangan",
    "PNSE.JK": "Barang Baku",
    "POLA.JK": "Perindustrian",
    "POLI.JK": "Barang Baku",
    "POLL.JK": "Properti & Real Estat",
    "POLU.JK": "Infrastruktur",
    "POOL.JK": "Keuangan",
    "PORT.JK": "Transportasi & Logistik",
    "POSA.JK": "Teknologi",
    "POWR.JK": "Infrastruktur",
    "PPGL.JK": "Perindustrian",
    "PPRE.JK": "Infrastruktur",
    "PPRI.JK": "Barang Konsumen Non-Primer",
    "PPRO.JK": "Properti & Real Estat",
    "PTPP.JK": "Infrastruktur",
    "PTDU.JK": "Perindustrian",
    "PTIS.JK": "Perindustrian",
    "PTMP.JK": "Perindustrian",
    "PTMR.JK": "Kesehatan",
    "PTPS.JK": "Barang Konsumen Primer",
    "PTRO.JK": "Energi",
    "PTSN.JK": "Teknologi",
    "PTSP.JK": "Barang Konsumen Non-Primer",
    "PUDP.JK": "Properti & Real Estat",
    "PURA.JK": "Perindustrian",
    "PURI.JK": "Properti & Real Estat",
    "PTPW.JK": "Infrastruktur",
    "PWON.JK": "Properti & Real Estat",
    "PYFA.JK": "Kesehatan",
    "PZZA.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD R ---
    "RAAM.JK": "Barang Konsumen Non-Primer",
    "RAFI.JK": "Barang Konsumen Non-Primer",
    "RAJA.JK": "Energi",
    "RALS.JK": "Barang Konsumen Non-Primer",
    "RANC.JK": "Barang Konsumen Primer",
    "RATU.JK": "Barang Konsumen Non-Primer",
    "RBMS.JK": "Properti & Real Estat",
    "RCCC.JK": "Transportasi & Logistik",
    "RDTX.JK": "Properti & Real Estat",
    "REAL.JK": "Properti & Real Estat",
    "RELF.JK": "Properti & Real Estat",
    "RELI.JK": "Keuangan",
    "RGAS.JK": "Infrastruktur",
    "RICY.JK": "Barang Konsumen Non-Primer",
    "RIGS.JK": "Transportasi & Logistik",
    "RIMO.JK": "Properti & Real Estat",
    "RISE.JK": "Properti & Real Estat",
    "RLCO.JK": "Barang Baku",
    "RMKE.JK": "Energi",
    "RMKO.JK": "Energi",
    "ROCK.JK": "Perindustrian",
    "RODA.JK": "Properti & Real Estat",
    "RONY.JK": "Transportasi & Logistik",
    "ROTI.JK": "Barang Konsumen Primer",
    "RSCH.JK": "Kesehatan",
    "RSGK.JK": "Kesehatan",
    "RUIS.JK": "Perindustrian",
    "RUNS.JK": "Teknologi",
    # --- ABJAD S ---
    "SAFE.JK": "Perindustrian",
    "SAGE.JK": "Properti & Real Estat",
    "SAMF.JK": "Barang Baku",
    "SAME.JK": "Kesehatan",
    "SAPX.JK": "Transportasi & Logistik",
    "SATU.JK": "Barang Konsumen Non-Primer",
    "SBAT.JK": "Barang Konsumen Non-Primer",
    "SBMA.JK": "Barang Baku",
    "SCCO.JK": "Barang Baku",
    "SCMA.JK": "Barang Konsumen Non-Primer",
    "SCNP.JK": "Barang Konsumen Non-Primer",
    "SCPI.JK": "Kesehatan",
    "SDMU.JK": "Transportasi & Logistik",
    "SDPC.JK": "Kesehatan",
    "SDRA.JK": "Keuangan",
    "SEMA.JK": "Perindustrian",
    "SFAN.JK": "Barang Konsumen Non-Primer",
    "SGER.JK": "Energi",
    "SGRO.JK": "Barang Konsumen Primer",
    "SHID.JK": "Barang Konsumen Non-Primer",
    "SHIP.JK": "Transportasi & Logistik",
    "SICO.JK": "Perindustrian",
    "SIDO.JK": "Kesehatan",
    "SILO.JK": "Kesehatan",
    "SIMA.JK": "Properti & Real Estat",
    "SIMP.JK": "Barang Konsumen Primer",
    "SINI.JK": "Energi",
    "SIPD.JK": "Keuangan",
    "SKBM.JK": "Barang Konsumen Primer",
    "SKLT.JK": "Barang Konsumen Primer",
    "SKRN.JK": "Perindustrian",
    "SKYB.JK": "Teknologi",
    "SLIS.JK": "Barang Konsumen Non-Primer",
    "SMAR.JK": "Barang Konsumen Primer",
    "SMBR.JK": "Barang Baku",
    "SMCB.JK": "Barang Baku",
    "SMDM.JK": "Properti & Real Estat",
    "SMDR.JK": "Transportasi & Logistik",
    "SMGA.JK": "Energi",
    "SMGR.JK": "Barang Baku",
    "SMKL.JK": "Teknologi",
    "SMKM.JK": "Barang Konsumen Non-Primer",
    "SMLE.JK": "Perindustrian",
    "SMMA.JK": "Keuangan",
    "SMMT.JK": "Energi",
    "SMRA.JK": "Properti & Real Estat",
    "SMRU.JK": "Energi",
    "SMSM.JK": "Barang Konsumen Non-Primer",
    "SNLK.JK": "Barang Konsumen Non-Primer",
    "SOCI.JK": "Transportasi & Logistik",
    "SOFA.JK": "Barang Konsumen Non-Primer",
    "SOHO.JK": "Kesehatan",
    "SOLA.JK": "Properti & Real Estat",
    "SONA.JK": "Barang Konsumen Non-Primer",
    "SOSS.JK": "Perindustrian",
    "SOTS.JK": "Barang Konsumen Non-Primer",
    "SOUL.JK": "Barang Konsumen Non-Primer",
    "SPMA.JK": "Barang Baku",
    "SPRE.JK": "Barang Konsumen Non-Primer",
    "SPTO.JK": "Barang Konsumen Non-Primer",
    "SQMI.JK": "Barang Baku",
    "SRAJ.JK": "Kesehatan",
    "SRIL.JK": "Barang Konsumen Non-Primer",
    "SRSN.JK": "Barang Baku",
    "SRTG.JK": "Keuangan",
    "SSIA.JK": "Properti & Real Estat",
    "SSMS.JK": "Barang Konsumen Primer",
    "SSTM.JK": "Barang Konsumen Non-Primer",
    "STAA.JK": "Barang Konsumen Primer",
    "STAR.JK": "Barang Konsumen Non-Primer",
    "STRK.JK": "Transportasi & Logistik",
    "STTP.JK": "Barang Konsumen Primer",
    "SUGI.JK": "Energi",
    "SULI.JK": "Barang Baku",
    "SUNI.JK": "Perindustrian",
    "SUPA.JK": "Barang Konsumen Primer",
    "SUPR.JK": "Infrastruktur",
    "SURI.JK": "Barang Baku",
    "SWAT.JK": "Barang Konsumen Non-Primer",
    "SWID.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD T ---
    "TALF.JK": "Barang Konsumen Primer",
    "TAMA.JK": "Infrastruktur",
    "TAMU.JK": "Transportasi & Logistik",
    "TAPG.JK": "Barang Konsumen Primer",
    "TARA.JK": "Properti & Real Estat",
    "TAXI.JK": "Transportasi & Logistik",
    "TAYS.JK": "Barang Konsumen Primer",
    "TBIG.JK": "Infrastruktur",
    "TBLA.JK": "Barang Konsumen Primer",
    "TBMS.JK": "Barang Baku",
    "TCID.JK": "Barang Konsumen Primer",
    "TCPI.JK": "Transportasi & Logistik",
    "TDPM.JK": "Barang Konsumen Non-Primer",
    "TECH.JK": "Teknologi",
    "TELE.JK": "Barang Konsumen Non-Primer",
    "TEBE.JK": "Transportasi & Logistik",
    "TFAS.JK": "Teknologi",
    "TFCO.JK": "Barang Baku",
    "TGKA.JK": "Barang Konsumen Primer",
    "TGRA.JK": "Infrastruktur",
    "TGUK.JK": "Barang Konsumen Primer",
    "TIFA.JK": "Keuangan",
    "TINS.JK": "Barang Baku",
    "TIRA.JK": "Barang Baku",
    "TIRT.JK": "Barang Baku",
    "TKIM.JK": "Barang Baku",
    "TLDM.JK": "Barang Konsumen Primer",
    "TLKM.JK": "Infrastruktur",
    "TMAS.JK": "Transportasi & Logistik",
    "TMPO.JK": "Barang Konsumen Non-Primer",
    "TNCA.JK": "Keuangan",
    "TOBA.JK": "Energi",
    "TOOL.JK": "Perindustrian",
    "TOPS.JK": "Infrastruktur",
    "TOSK.JK": "Barang Konsumen Primer",
    "TOTL.JK": "Infrastruktur",
    "TOTO.JK": "Barang Baku",
    "TOWR.JK": "Infrastruktur",
    "TOYS.JK": "Barang Konsumen Non-Primer",
    "TPIA.JK": "Barang Baku",
    "TPMA.JK": "Transportasi & Logistik",
    "TRAM.JK": "Transportasi & Logistik",
    "TRGU.JK": "Barang Konsumen Primer",
    "TRIL.JK": "Perindustrian",
    "TRIM.JK": "Keuangan",
    "TRIN.JK": "Properti & Real Estat",
    "TRIO.JK": "Barang Konsumen Non-Primer",
    "TRIS.JK": "Barang Konsumen Non-Primer",
    "TRJA.JK": "Transportasi & Logistik",
    "TRON.JK": "Teknologi",
    "TRST.JK": "Barang Baku",
    "TRUE.JK": "Properti & Real Estat",
    "TRUK.JK": "Transportasi & Logistik",
    "TRUS.JK": "Perindustrian",
    "TSPC.JK": "Kesehatan",
    "TUGU.JK": "Keuangan",
    "TYRE.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD U ---
    "UANG.JK": "Barang Baku",
    "UCID.JK": "Barang Konsumen Non-Primer",
    "UDNG.JK": "Barang Konsumen Primer",
    "UFOE.JK": "Barang Konsumen Non-Primer",
    "ULTJ.JK": "Barang Konsumen Primer",
    "UNIC.JK": "Barang Baku",
    "UNIQ.JK": "Infrastruktur",
    "UNIT.JK": "Barang Konsumen Non-Primer",
    "UNSP.JK": "Barang Konsumen Primer",
    "UNTD.JK": "Barang Konsumen Non-Primer",
    "UNTR.JK": "Perindustrian",
    "UNVR.JK": "Barang Konsumen Primer",
    "URBN.JK": "Properti & Real Estat",
    "UVCR.JK": "Teknologi",
    # --- ABJAD V ---
    "VAST.JK": "Properti & Real Estat",
    "VERN.JK": "Barang Konsumen Non-Primer",
    "VICI.JK": "Barang Konsumen Primer",
    "VICO.JK": "Energi",
    "VINS.JK": "Teknologi",
    "VIVA.JK": "Barang Konsumen Non-Primer",
    "VISI.JK": "Barang Konsumen Non-Primer",
    "VOKS.JK": "Barang Baku",
    "VRNA.JK": "Keuangan",
    "VTNY.JK": "Barang Konsumen Non-Primer",
    # --- ABJAD W ---
    "WAPO.JK": "Perindustrian",
    "WBSA.JK": "Barang Konsumen Primer",
    "WEGE.JK": "Infrastruktur",
    "WEHA.JK": "Transportasi & Logistik",
    "WGSH.JK": "Teknologi",
    "WICO.JK": "Barang Konsumen Primer",
    "WIDI.JK": "Barang Baku",
    "WIFI.JK": "Infrastruktur",
    "WIIM.JK": "Barang Konsumen Primer",
    "WIKA.JK": "Infrastruktur",
    "WINE.JK": "Barang Konsumen Primer",
    "WINR.JK": "Properti & Real Estat",
    "WINS.JK": "Transportasi & Logistik",
    "WMPP.JK": "Barang Konsumen Primer",
    "WMUU.JK": "Barang Konsumen Primer",
    "WOMF.JK": "Keuangan",
    "WOOD.JK": "Barang Konsumen Non-Primer",
    "WOWS.JK": "Properti & Real Estat",
    "WSBP.JK": "Barang Baku",
    "WSKT.JK": "Infrastruktur",
    "WTON.JK": "Barang Baku",
    # --- ABJAD Y sampai Z ---
    "YELO.JK": "Teknologi",
    "YOII.JK": "Barang Konsumen Non-Primer",
    "YPAS.JK": "Barang Baku",
    "YULE.JK": "Keuangan",
    "YUPI.JK": "Barang Konsumen Primer",
    "ZATA.JK": "Barang Konsumen Non-Primer",
    "ZBRA.JK": "Transportasi & Logistik",
    "ZINC.JK": "Barang Baku",
    "ZONE.JK": "Barang Konsumen Non-Primer",
    "ZYRX.JK": "Teknologi",
}
